### ISSUE TITLE
The MTU set by rdcu_rmap_init() is never used

### ISSUE THREAD

**Issue by dloidolt** [aluntzer/plato-rdcu#8]
The mtu set by the initialisation of the rdcu control library (`rdcu_rmap_init()` in `lib/rdcu_rmap.c`) is not used for the RMAP packets.

I have two solutions to that problem:
1. Implement a function which returns the user the data_mtu.
```c 
int get_data_mtu(void) {
    return data_mtu;
}
```
The user can then use this function to set the data mtu for the data transfer functions:
```c 
rdcu_sync_mirror_to_sram(rdcu_data_adr, size, get_data_mtu());
```

2. simplify the data transfer functions in that way that the user can only set the mtu size with the rdcu_rmap_init function.
The data transfer functions do the mtu lookup intern and have no interface to choose the mtu size.
`int rdcu_sync_mirror_to_sram(uint32_t addr,  uint32_t size);` instead of `int rdcu_sync_mirror_to_sram(uint32_t addr,  uint32_t size, uint32_t mtu); `

**Comment by aluntzer** [comment]
added `size_t rdcu_get_data_mtu(void); `
